name = "weather"
main = "index.js"
compatibility_date = "2024-04-02"
account_id = "853b20cad3dcd818d5f46c1255ce604f"

# 关键：只留变量名，不填具体内容！
[vars]
QWEATHER_KEY = ""
CAIYUN_TOKEN = ""
TG_BOT_TOKEN = ""
TG_CHAT_ID = ""

[[kv_namespaces]]
binding = "WEATHER_KV"
id = "17e55cf312b84eab8b9647b1e0aa1269"
=======
[triggers]
crons = ["0 7-23 * * *"] # 每小时的第 0 分钟执行
>>>>>>> 7104864225b3f3e7cf36a6456fb98f5db1aa4c9c
