name = "weather"
main = "index.js"
compatibility_date = "2024-04-02"
account_id = "853b20cad3dcd818d5f46c1255ce604f"

<<<<<<< HEAD
# 关键：在这里列出所有变量名，这样部署时就不会被覆盖删除了
[vars]
QWEATHER_KEY = "5cd564a31a5c4ec8834bde5048729cf4"
CAIYUN_TOKEN = "ilENMw3Qmgaj3jFT"
TG_BOT_TOKEN = "8717238043:AAG5kQroG27ZUCkehqOk5KInMvvPlOfgT3c"
TG_CHAT_ID = "663833360"

[[kv_namespaces]]
binding = "WEATHER_KV"
id = "17e55cf312b84eab8b9647b1e0aa1269"
=======
[triggers]
crons = ["0 7-23 * * *"] # 每小时的第 0 分钟执行
>>>>>>> 7104864225b3f3e7cf36a6456fb98f5db1aa4c9c
