name = "weather"
main = "index.js"
compatibility_date = "2024-04-02"

[vars]
# 保持空值即可，部署时会由 GitHub 自动注入
TG_BOT_TOKEN = ""
TG_CHAT_ID = ""
QWEATHER_KEY = ""
CAIYUN_TOKEN = ""

[[kv_namespaces]]
binding = "WEATHER_KV"
id = "17e55cf312b84eab8b9647b1e0aa1269"
