- name: Deploy to Cloudflare Workers
  env:
    TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
    QWEATHER_KEY: ${{ secrets.QWEATHER_KEY }}
    CAIYUN_TOKEN: ${{ secrets.CAIYUN_TOKEN }}
  uses: cloudflare/wrangler-action@v3
  with:
    apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    vars: |
      TG_BOT_TOKEN
      TG_CHAT_ID
      QWEATHER_KEY
      CAIYUN_TOKEN
